username: allen.g.wagner@gmail.com
password: qcyhjrFr9Mw9Ak7!

positions:
- UX
- User Experience Design
- Interaction Design

locations:
- Remote
- Ohio

# --------- Optional Parameters -------
# uploads:
Resume: C:\Users\Waggles\Desktop\AllenWagner_Resume.pdf
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


output_filename: C:\Users\Waggles\Desktop\output.csv
# - # PATH TO OUTPUT FILE (default output.csv)

blacklist:
- Nationwide

#blackListTitles:
#- # Add job titles you want to ignore
